[package]
name = "gpkg-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.27.0"
geo-types = "*"
gpkg-derive = { version = "*", path = "../gpkg-derive" }
wkb = "0.7.1"
